[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
piggy_bank = "C6BYBup5zxh5mmGkeuBUdEQKEbjhTf34EtSr9uNFqPxW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
